### ISSUE TITLE
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://reddsjukeboxdev.herokuapp.com/addSongToPlaylist. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)

### ISSUE THREAD

**Issue by mitalthakkar31** [kdechant/angular5-httpclient-demo#4]
I am using http.post method for one of my Project but i got an error in console on post "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://reddsjukeboxdev.herokuapp.com/addSongToPlaylist. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)"

Bakend API is working fine.Here is my Code of service file from where i am using http.post method
const httpOptions = {
   headers: new HttpHeaders({ 'Content-Type': 'application/json' })
};
addToPlaylist(data) {
        console.log("inservice data is",data);
         let body = JSON.stringify(data);
         return this.http.post(this.api_endpoint+'addSongToPlaylist', body, httpOptions);
     }

Please help with this error

**Comment by kdechant** [comment]
Sorry, I can only provide support for the demo app shown in this repository. I can't provide support for your project. (I may write another blog post about Angular and CORS at some point though, as it's a confusing topic.)
